In [10]:
import scipy

mat = scipy.matrix([
        [2, 1, 0, 0, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1]
    ])
y = scipy.array([1, 1, 1, 0])

'''
mat = scipy.matrix([
        [1,1, 1],
        [2,1, 1],
        [2,2, 1],
        [-1,-1, 1],
        [1, -1, 1]
    ])
y = scipy.array([1, 1, 1, 0, 0])
'''

sigmoid = lambda x: 1.0/(1+scipy.exp(-x))

def _intercept_dot(w, X):
    z =  X *scipy.asmatrix(w[:-1]).T  + w[-1]
    return z

def _loss(w):
    z = _intercept_dot(w, mat)
    loss = scipy.dot(y, scipy.log(sigmoid(z))) + scipy.dot(1-y, scipy.log(1-sigmoid(z)))
    return -loss+0.05*scipy.dot(w,w)

n = mat.shape[1]
from scipy.optimize import minimize
opt = minimize(_loss, scipy.ones(n+1))
w0 = opt['x']
print opt

   status: 0
  success: True
     njev: 16
     nfev: 144
 hess_inv: array([[ 1.96432224, -0.80912115, -0.80912115, -1.5154271 , -0.82702762,
        -0.82703084, -0.03470906],
       [-0.80912115,  4.3477774 ,  3.3477774 ,  1.32628462,  0.67095733,
         0.67095591, -1.02574758],
       [-0.80912115,  3.3477774 ,  4.3477774 ,  1.32628462,  0.67095733,
         0.67095591, -1.02574758],
       [-1.5154271 ,  1.32628462,  1.32628462,  5.27779872,  0.26667125,
         0.26667911,  0.37796406],
       [-0.82702762,  0.67095733,  0.67095733,  0.26667125,  1.98131303,
         0.98131345, -0.26541762],
       [-0.82703084,  0.67095591,  0.67095591,  0.26667911,  0.98131345,
         1.98131388, -0.26541567],
       [-0.03470906, -1.02574758, -1.02574758,  0.37796406, -0.26541762,
        -0.26541567,  1.43450882]])
      fun: 0.7306450282703472
        x: array([ 1.16573539,  0.45600022,  0.45600022,  0.89735182, -1.55557555,
       -1.55557556,  0.2537516 ])
  message: 'Optimization te

In [11]:
def predict(x):
    z = _intercept_dot(w0, x)
    return sigmoid(z), sigmoid(1-z)

print predict([3,0,0,0,1,1])

(matrix([[ 0.65470975]]), matrix([[ 0.58908724]]))


In [15]:
class LogisticRegression:
    def __init__(self, lbd = 0.5):
        self._w = None
        self._lbd = lbd

    def _intercept_dot(self, w, X):
        z =  X *scipy.asmatrix(w[:-1]).T  + w[-1]
        return z

    def train(self, X, y):
        n_features = X.shape[1]
        n_data = X.shape[0]
        #self._w = np.ones(n_features + 1)
        def _loss(w):
            z = self._intercept_dot(w, X)
            loss = scipy.dot(y, scipy.log(sigmoid(z))) + scipy.dot(1-y, scipy.log(1-sigmoid(z)))
            return -loss+self._lbd*scipy.dot(w,w)

        opt = scipy.optimize.minimize(_loss, scipy.ones(n_features + 1))
        print opt
        #print X.shape, np.hstack([X, np.ones(n_data)]).shape
        self._w = opt['x']

    def predict(self, x):
        z = _intercept_dot(self._w, x)
        return sigmoid(z), 1 - sigmoid(z)

m=LogisticRegression()
m.train(mat, y)
print m.predict([3,0,0,0,1,1])

   status: 0
  success: True
     njev: 10
     nfev: 90
 hess_inv: array([[ 0.53368234, -0.09811254, -0.09812876, -0.04504567, -0.05071851,
        -0.05072408, -0.27886457],
       [-0.09811254,  1.0192868 ,  0.019263  , -0.01495837,  0.02357784,
         0.02357568, -0.06315863],
       [-0.09812876,  0.019263  ,  1.01923918, -0.01498394,  0.02354474,
         0.02354258, -0.06318232],
       [-0.04504567, -0.01495837, -0.01498394,  0.93018467, -0.00553229,
        -0.0055339 , -0.0512121 ],
       [-0.05071851,  0.02357784,  0.02354474, -0.00553229,  0.87924548,
        -0.1207602 , -0.09040728],
       [-0.05072408,  0.02357568,  0.02354258, -0.0055339 , -0.1207602 ,
         0.87923413, -0.09041267],
       [-0.27886457, -0.06315863, -0.06318232, -0.0512121 , -0.09040728,
        -0.09041267,  0.80127491]])
      fun: 1.7813333178451414
        x: array([ 0.55453751,  0.18575141,  0.18575142,  0.26787062, -0.45633611,
       -0.45633611,  0.18303575])
  message: 'Optimization ter

ValueError: shapes (4,6) and (1,6) not aligned: 6 (dim 1) != 1 (dim 0)

In [68]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(mat, y)

model.predict(scipy.array([1,1,1]).reshape(1, -1))

array([1])

In [71]:
model.coef_

array([[ 0.46283909,  0.98686941, -0.07904775]])

In [93]:
scipy.vstack([mat, scipy.ones(4)])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

((4,), (4, 6))